Fix karma, readme updates, move utils to own file
ethereumjs/rlp pull request #109
Opened 2022-01-09 02:04 UTC by ryanio

This PR updates the karma-typescript dependency to a built version from master using gitpkg for the unreleased [fix](https://github.com/monounity/karma-typescript/pull/502).

It also includes some refactoring and readme updates.

2022-01-09 02:23 UTC, paulmillr commented
I know using 3 files instead of 1 is much more readable, just not sure about ESM support - or Deno support. 

I have been making my stuff work with those, and there are some things that you need to take into account. 

For example, in Deno you can't import .js files, and you need to specify extensions in imports. In ESM, you cannot import .ts files.

My suggestion would be to move everything into one file and place it in root. After that, after the release, we could work on .esm tsconfig and Deno package. I could help here

2022-01-09 02:25 UTC, paulmillr commented
I have worked around "many files" thing in bls12-381 by using export maps but we definitely don't want to force Deno users to do that (a separate .json file)

2022-01-09 03:32 UTC, ryanio commented
@paulmillr sounds good, thanks for the feedback, we already had 2 files (index, types) so I thought a third for utils would be harmless (the improved readability is great), but I am also in favor of broader ecosystem support, so whatever we need to do here - if it is one file then that's fine by me too.

Appreciate your help with esm and Deno insights, we can probably bring these learnings over to our monorepo as well.

2022-01-09 03:40 UTC, ryanio commented
For the karma-typescript fix, I wrote some of my findings in this comment: https://github.com/ethereumjs/ethereumjs-monorepo/pull/1602#issuecomment-1008222864

2022-01-09 04:51 UTC, ryanio commented
@talentlessguy has helped us with Deno compatibility in the past, let us know how this PR is looking

2022-01-09 18:40 UTC, paulmillr requested changes
Looks great to me!

2022-01-09 18:40 UTC, paulmillr commented on .github/workflows/build.yml
> +        node-version: [12, 13, 14, 16]
Let's remove v13, it has not been supported for many years.

2022-01-09 22:59 UTC, paulmillr approved these changes

2022-01-10 02:04 UTC, ryanio commented
thanks!

2022-01-10 02:04 UTC, merged